### ISSUE TITLE
Allow to set statement error?

### ISSUE THREAD

**Issue by marcosnils** [play-with-go/preguide#194]
Sometimes, you want to showcase a step where some of the source statements could produce an error. The way to solve that today is through some hackery to assert the code in the step i.e:

```cue
Steps: gopher_update_fail: preguide.#Command & {
	Source: """
cd \(Defs.gopher_dir)
# We launch this in a subshell to assert the status code
code=$(\(Defs.cmdgo.get) -u -v \(Defs.public_mod)@main; echo $?)

# Assert that status code is correct or fail
[ $code == 2 ] || false
"""
}
```
Does it even make sense to provide a way to allow the user to specify that some statements are expected to output a specific code?

**Comment by myitcv** [comment]
If you start the command with `!` then that should achieve what you want, e.g.:

https://github.com/play-with-go/preguide/blob/e5ab271ba2e92313c56754702035862b357bb48d/cmd/preguide/testdata/all_directives.txt#L74

When that command is printed, the `!` is elided.
